import type { Metadata } from "next";
import OrgPlainLayout from "@/components/organisms/layouts/OrgPlainLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <OrgPlainLayout>
     {children}
   </OrgPlainLayout>
  );
}
